Repository EngineSquared/EngineSquared, pull requests merged in 2024-10, with the labels that each got.

#16 Compilation system
  .gitignore
  README.md
  src/hw.cpp
  src/hw.h
  xmake.lua
Labels: enhancement

#19 ci: remove execution of mirroring job on pull request event
  .github/workflows/mirror.yml
Labels: bug, ci

#21 ci: compilation and unit test check
  .github/workflows/mirror.yml
  src/add.cpp
  src/add.h
  tests/dummy.cpp
  tests/main.cpp
  xmake.lua
Labels: ci

#22 docs: add description and commands in README
  README.md
Labels: documentation

#23 feat(core): basic game engine implementation
  src/add.cpp
  src/add.h
  src/engine/Engine.hpp
  src/engine/entity/Entity.cpp
  src/engine/entity/Entity.hpp
  src/engine/entity/Entity.inl
  src/engine/registry/Registry.cpp
  src/engine/registry/Registry.hpp
  src/engine/registry/Registry.inl
  src/hw.cpp
  src/hw.h
  tests/dummy.cpp
  tests/engine/registry_test.cpp
  xmake.lua
Labels: enhancement

#29 feat(core): Camera3D component
  src/plugin/camera/component/Camera3D.hpp
  xmake.lua
Labels: enhancement

#30 feat(core): collider systems
  src/engine/entity/Entity.hpp
  src/engine/entity/Entity.inl
  src/plugin/collision/Collision.hpp
  src/plugin/collision/component/BoxCollider3D.hpp
  src/plugin/collision/resource/CollisionStorage.cpp
  src/plugin/collision/resource/CollisionStorage.hpp
  src/plugin/collision/system/CollisionChecker.cpp
  src/plugin/collision/system/CollisionChecker.hpp
  tests/engine/RegistryTest.cpp
  tests/plugin/collision/CollisionTest.cpp
  xmake.lua
Labels: enhancement

#31 ci: automatic commit norm verification
  .github/workflows/commit_norm_check.yml
Labels: ci

#25 docs: doxygen support
  .github/workflows/deploy_doxygen_page.yml
  .github/workflows/mirror.yml
  .gitignore
  Doxyfile.cfg
  README.md
Labels: documentation

#27 ci: coding style checker
  .clang-format
  .clang-format-ignore
  .github/workflows/linter.yaml
  README.md
  src/engine/Engine.hpp
  src/engine/entity/Entity.cpp
  src/engine/entity/Entity.hpp
  src/engine/registry/Registry.cpp
  src/engine/registry/Registry.hpp
  src/plugin/camera/component/Camera3D.hpp
  src/plugin/collision/Collision.hpp
  src/plugin/collision/component/BoxCollider3D.hpp
  src/plugin/collision/resource/CollisionStorage.cpp
  src/plugin/collision/resource/CollisionStorage.hpp
  src/plugin/collision/system/CollisionChecker.cpp
  src/plugin/collision/system/CollisionChecker.hpp
  src/plugin/object/Object.hpp
  src/plugin/object/component/MeshID.hpp
  src/plugin/object/component/Transform.hpp
  src/plugin/object/resource/AssetsManager.hpp
  src/plugin/object/utils/AssetID.hpp
  tests/engine/RegistryTest.cpp
  tests/main.cpp
  tests/plugin/collision/CollisionTest.cpp
  tests/plugin/object/AssetsManagerTest.cpp
  tests/plugin/object/TransformTest.cpp
Labels: ci

#26 feat(core): input plugin
  src/plugin/input/resource/InputManager.hpp
  src/plugin/window/exception/WindowError.hpp
  src/plugin/window/resource/Window.cpp
  src/plugin/window/resource/Window.hpp
  xmake.lua
Labels: enhancement

#32 feat(core): mass spring plugin
  src/engine/Engine.hpp
  src/plugin/collision/system/SoftBodyCollision.cpp
  src/plugin/collision/system/SoftBodyCollision.hpp
  src/plugin/physics/component/SoftBodyNode.hpp
  src/plugin/physics/component/SoftBodySpring.hpp
  src/plugin/physics/system/VelocityIntegration.cpp
  src/plugin/physics/system/VelocityIntegration.hpp
  src/plugin/time/resource/RealTimeProvider.cpp
  src/plugin/time/resource/RealTimeProvider.hpp
  src/plugin/time/system/RealTimeUpdater.cpp
  src/plugin/time/system/RealTimeUpdater.hpp
  tests/plugin/physics/SoftBodyCollisionTest.cpp
  tests/plugin/physics/VelocityIntegrationTest.cpp
  tests/utils/Sleep.hpp
  xmake.lua
Labels: enhancement

#43 feat(core): entity temporary components
  src/engine/entity/Entity.hpp
  tests/engine/EntityTest.cpp
Labels: enhancement
