Repository EngineSquared/EngineSquared, pull requests merged in 2024-12, with the labels that each got.

#67 refactor: fix sonarcloud issues
  .gitignore
  src/engine/src/entity/Entity.cpp
  src/engine/src/entity/Entity.hpp
  src/engine/src/registry/Registry.cpp
  src/engine/src/registry/Registry.hpp
  src/engine/src/registry/Registry.inl
  src/engine/tests/engine/EntityTest.cpp
  src/engine/tests/engine/RegistryTest.cpp
  src/plugin/colors/src/utils/Color.hpp
  src/plugin/input/src/resource/InputManager.hpp
  src/plugin/object/src/utils/AssetID.hpp
  src/plugin/object/tests/AssetsManagerTest.cpp
  src/plugin/object/tests/TransformTest.cpp
  src/plugin/physics/src/component/SoftBodyNode.hpp
  src/plugin/physics/src/component/SoftBodySpring.hpp
  src/plugin/physics/src/system/SoftBodyCollision.cpp
  src/plugin/physics/src/system/VelocityIntegration.cpp
  src/plugin/physics/tests/CollisionsTest2D.cpp
  src/plugin/physics/tests/SoftBodyCollisionsTest.cpp
  src/plugin/physics/tests/VelocityIntegrationTest.cpp
  src/plugin/scene/src/resource/SceneManager.hpp
  src/plugin/scene/src/utils/AScene.hpp
  src/plugin/scene/tests/SceneTest.cpp
  src/plugin/time/src/resource/RealTimeProvider.cpp
  src/plugin/time/src/resource/RealTimeProvider.hpp
  src/plugin/ui/src/system/ButtonClick.cpp
  src/plugin/ui/src/system/UpdateButtonState.cpp
  src/plugin/ui/src/system/UpdateButtonTexture.cpp
  src/plugin/ui/tests/Button.cpp
  src/plugin/vk-wrapper/src/VkWrapper.cpp
  src/plugin/vk-wrapper/src/VkWrapper.hpp
  src/plugin/vk-wrapper/src/debugMessenger/DebugMessenger.cpp
  src/plugin/vk-wrapper/src/debugMessenger/DebugMessenger.hpp
  src/plugin/vk-wrapper/src/device/PhysicalDevice.cpp
  src/plugin/vk-wrapper/src/device/PhysicalDevice.hpp
  src/plugin/vk-wrapper/src/exception/VkWrapperError.hpp
  src/plugin/vk-wrapper/src/framebuffer/Framebuffer.cpp
  src/plugin/vk-wrapper/src/framebuffer/Framebuffer.hpp
  src/plugin/vk-wrapper/src/graphicsPipeline/GraphicsPipeline.cpp
  src/plugin/vk-wrapper/src/imageView/ImageView.cpp
  src/plugin/vk-wrapper/src/imageView/ImageView.hpp
  src/plugin/vk-wrapper/src/instance/Instance.cpp
  src/plugin/vk-wrapper/src/instance/Instance.hpp
  src/plugin/vk-wrapper/src/shaderModule/ShaderModule.cpp
  src/plugin/vk-wrapper/src/shaderModule/ShaderModule.hpp
  src/plugin/vk-wrapper/src/swapChain/SwapChain.cpp
  src/plugin/vk-wrapper/src/swapChain/SwapChain.hpp
  src/plugin/window/src/exception/WindowError.hpp
  src/plugin/window/src/resource/Window.cpp
  src/plugin/window/src/resource/Window.hpp
  src/utils/clock/src/Clock.cpp
  src/utils/clock/src/Clock.hpp
  src/utils/string/src/String.cpp
  src/utils/string/src/String.hpp
Labels: refactor

#68 feat(schedulers): system schedulers
  .github/workflows/mirror.yml
  src/engine/src/Engine.hpp
  src/engine/src/registry/Registry.cpp
  src/engine/src/registry/Registry.hpp
  src/engine/src/registry/Registry.inl
  src/engine/src/registry/ScheduleLabel.hpp
  src/engine/src/scheduler/AScheduler.hpp
  src/engine/src/scheduler/FixedTimeUpdate.cpp
  src/engine/src/scheduler/FixedTimeUpdate.hpp
  src/engine/src/scheduler/IScheduler.hpp
  src/engine/src/scheduler/RelativeTimeUpdate.cpp
  src/engine/src/scheduler/RelativeTimeUpdate.hpp
  src/engine/src/scheduler/Startup.cpp
  src/engine/src/scheduler/Startup.hpp
  src/engine/src/scheduler/Update.cpp
  src/engine/src/scheduler/Update.hpp
  src/engine/tests/engine/FixedUpdateTest.cpp
  src/engine/tests/engine/RegistryTest.cpp
  src/engine/tests/engine/RelativeUpdateTest.cpp
  src/engine/tests/engine/StartupTest.cpp
  src/engine/xmake.lua
  src/plugin/physics/src/system/SoftBodyCollision.cpp
  src/plugin/physics/src/system/VelocityIntegration.cpp
  src/plugin/physics/tests/SoftBodyCollisionsTest.cpp
  src/plugin/physics/tests/VelocityIntegrationTest.cpp
  src/plugin/physics/xmake.lua
  src/plugin/time/.gitignore
  src/plugin/time/src/resource/RealTimeProvider.cpp
  src/plugin/time/src/resource/RealTimeProvider.hpp
  src/plugin/time/src/system/RealTimeUpdater.cpp
  src/plugin/time/src/system/RealTimeUpdater.hpp
  src/plugin/time/xmake.lua
  src/utils/clock/src/Clock.cpp
  src/utils/clock/src/Clock.hpp
  src/utils/clock/tests/ClockTest.cpp
  src/utils/clock/tests/main.cpp
  src/utils/clock/xmake.lua
  xmake.lua
Labels: enhancement

#69 Fix last sonar errors
  src/plugin/object/src/resource/AssetsManager.hpp
  src/plugin/ui/tests/Button.cpp
Labels: refactor

#72 feat(object): obj loader
  src/plugin/object/src/Object.hpp
  src/plugin/object/src/component/Mesh.hpp
  src/plugin/object/src/component/Vertex.hpp
  src/plugin/object/src/resource/OBJLoader.cpp
  src/plugin/object/src/resource/OBJLoader.hpp
  src/plugin/object/tests/MeshTest.cpp
  src/plugin/object/tests/OBJLoaderTest.cpp
  src/plugin/object/tests/VertexTest.cpp
  src/plugin/object/tests/assets/cube.obj
  src/plugin/object/tests/assets/not_obj.txt
  src/plugin/object/xmake.lua
  src/plugin/scene/xmake.lua
  src/plugin/utils/xmake.lua
  src/plugin/vk-wrapper/xmake.lua
  xmake.lua
Labels: enhancement, test
