Repository EngineSquared/EngineSquared, pull requests merged in 2024-11, with the labels that each got.

#47 feat(vk-wrapper): vulkan API wrapper
  .clang-format
  .gitignore
  src/engine/Engine.hpp
  src/engine/entity/Entity.cpp
  src/engine/entity/Entity.hpp
  src/engine/registry/Registry.cpp
  src/engine/registry/Registry.hpp
  src/engine/registry/Registry.inl
  src/plugin/collision/Collision.hpp
  src/plugin/collision/system/CollisionChecker.cpp
  src/plugin/utils/export.h
  src/plugin/vk-wrapper/VkWrapper.cpp
  src/plugin/vk-wrapper/VkWrapper.hpp
  src/plugin/vk-wrapper/command/Command.cpp
  src/plugin/vk-wrapper/command/Command.hpp
  src/plugin/vk-wrapper/config.h
  src/plugin/vk-wrapper/debugMessenger/DebugMessenger.cpp
  src/plugin/vk-wrapper/debugMessenger/DebugMessenger.hpp
  src/plugin/vk-wrapper/device/LogicalDevice.cpp
  src/plugin/vk-wrapper/device/LogicalDevice.hpp
  src/plugin/vk-wrapper/device/PhysicalDevice.cpp
  src/plugin/vk-wrapper/device/PhysicalDevice.hpp
  src/plugin/vk-wrapper/exception/VkWrapperError.hpp
  src/plugin/vk-wrapper/framebuffer/Framebuffer.cpp
  src/plugin/vk-wrapper/framebuffer/Framebuffer.hpp
  src/plugin/vk-wrapper/graphicsPipeline/GraphicsPipeline.cpp
  src/plugin/vk-wrapper/graphicsPipeline/GraphicsPipeline.hpp
  src/plugin/vk-wrapper/imageView/ImageView.cpp
  src/plugin/vk-wrapper/imageView/ImageView.hpp
  src/plugin/vk-wrapper/instance/Instance.cpp
  src/plugin/vk-wrapper/instance/Instance.hpp
  src/plugin/vk-wrapper/queueFamilies/QueueFamilies.cpp
  src/plugin/vk-wrapper/queueFamilies/QueueFamilies.hpp
  src/plugin/vk-wrapper/renderPass/RenderPass.cpp
  src/plugin/vk-wrapper/renderPass/RenderPass.hpp
  src/plugin/vk-wrapper/shaderModule/ShaderModule.cpp
  src/plugin/vk-wrapper/shaderModule/ShaderModule.hpp
  src/plugin/vk-wrapper/surface/Surface.cpp
  src/plugin/vk-wrapper/surface/Surface.hpp
  src/plugin/vk-wrapper/swapChain/SwapChain.cpp
  src/plugin/vk-wrapper/swapChain/SwapChain.hpp
  src/plugin/window/exception/WindowError.hpp
  src/plugin/window/resource/Window.cpp
  src/plugin/window/resource/Window.hpp
  tests/engine/EntityTest.cpp
  tests/engine/RegistryTest.cpp
  xmake.lua
Labels: documentation, enhancement

#46 feat(ui): add ui plugin with button management
  src/plugin/collision/Collision.hpp
  src/plugin/collision/component/BoxCollider2D.hpp
  src/plugin/collision/utils/CollisionBetweenCollider.cpp
  src/plugin/collision/utils/CollisionBetweenCollider.hpp
  src/plugin/colors/Colors.hpp
  src/plugin/colors/utils/Color.hpp
  src/plugin/input/resource/InputManager.hpp
  src/plugin/math/Math.cpp
  src/plugin/math/Math.hpp
  src/plugin/object/component/Transform.hpp
  src/plugin/object/resource/AssetsManager.hpp
  src/plugin/object/utils/AssetID.hpp
  src/plugin/tools/HasChanged.hpp
  src/plugin/tools/Tools.hpp
  src/plugin/ui/UI.hpp
  src/plugin/ui/component/Button.hpp
  src/plugin/ui/component/Sprite2D.hpp
  src/plugin/ui/system/ButtonClick.cpp
  src/plugin/ui/system/ButtonClick.hpp
  src/plugin/ui/system/UpdateButtonState.cpp
  src/plugin/ui/system/UpdateButtonState.hpp
  src/plugin/ui/system/UpdateButtonTexture.cpp
  src/plugin/ui/system/UpdateButtonTexture.hpp
  tests/plugin/collision/CollisionBetweenCollider.cpp
  tests/plugin/ui/Button.cpp
  xmake.lua
Labels: enhancement

#50 feat(Scene): add Scene Management
  src/engine/registry/Registry.cpp
  src/engine/registry/Registry.hpp
  src/plugin/scene/Scene.hpp
  src/plugin/scene/resource/SceneManager.cpp
  src/plugin/scene/resource/SceneManager.hpp
  src/plugin/scene/system/UpdateScene.cpp
  src/plugin/scene/system/UpdateScene.hpp
  src/plugin/scene/utils/AScene.hpp
  tests/plugin/scene/SceneTest.cpp
  xmake.lua
Labels: enhancement

#57 doc(CONTRIBUTING): add the guidelines
  CONTRIBUTING.md
Labels: documentation

#56 feat(log): add logging library using `spdlog`
  src/plugin/scene/src/resource/SceneManager.cpp
  src/plugin/scene/src/resource/SceneManager.hpp
  src/plugin/scene/tests/SceneTest.cpp
  src/plugin/scene/xmake.lua
  src/plugin/utils/xmake.lua
  src/plugin/vk-wrapper/src/VkWrapper.cpp
  src/plugin/vk-wrapper/src/debugMessenger/DebugMessenger.cpp
  src/plugin/vk-wrapper/src/debugMessenger/DebugMessenger.hpp
  src/plugin/vk-wrapper/xmake.lua
  src/utils/log/src/Logger.hpp
  src/utils/log/xmake.lua
  src/utils/string/src/String.cpp
  src/utils/string/src/String.hpp
  src/utils/string/tests/StringTest.cpp
  src/utils/string/tests/main.cpp
  src/utils/string/xmake.lua
  xmake.lua
Labels: enhancement

#60 refactor(Log): remove xmake add_files of cpp where cpp doesn't exist
  src/utils/log/xmake.lua
Labels: bug, build

#64 fix: soft body physics breaking at low framerates
  src/plugin/physics/src/system/SoftBodyCollision.cpp
  src/plugin/physics/src/system/VelocityIntegration.cpp
Labels: bug
