Repository EngineSquared/EngineSquared, pull requests merged in 2025-04, with the labels that each got.

#154 feat(Physics): JoltPhysics integration
  src/plugin/physics/.gitignore
  src/plugin/physics/src/JoltPhysics.hpp
  src/plugin/physics/src/Physics.hpp
  src/plugin/physics/src/component/ABABCollision3D.hpp
  src/plugin/physics/src/component/BoxCollider3D.hpp
  src/plugin/physics/src/component/ParticleBoxCollision.hpp
  src/plugin/physics/src/component/RigidBody3D.hpp
  src/plugin/physics/src/component/SoftBodyNode.hpp
  src/plugin/physics/src/component/SoftBodySpring.hpp
  src/plugin/physics/src/plugin/PluginPhysics.cpp
  src/plugin/physics/src/plugin/PluginPhysics.hpp
  src/plugin/physics/src/resource/PhysicsManager.cpp
  src/plugin/physics/src/resource/PhysicsManager.hpp
  src/plugin/physics/src/system/CollisionCheckerABAB.cpp
  src/plugin/physics/src/system/CollisionCheckerABAB.hpp
  src/plugin/physics/src/system/InitJoltPhysics.cpp
  src/plugin/physics/src/system/InitJoltPhysics.hpp
  src/plugin/physics/src/system/InitPhysicsManager.cpp
  src/plugin/physics/src/system/InitPhysicsManager.hpp
  src/plugin/physics/src/system/PhysicsUpdate.cpp
  src/plugin/physics/src/system/PhysicsUpdate.hpp
  src/plugin/physics/src/system/ShutdownJoltPhysics.cpp
  src/plugin/physics/src/system/ShutdownJoltPhysics.hpp
  src/plugin/physics/src/system/SoftBodyCollision.cpp
  src/plugin/physics/src/system/SoftBodyCollision.hpp
  src/plugin/physics/src/system/VelocityIntegration.cpp
  src/plugin/physics/src/system/VelocityIntegration.hpp
  src/plugin/physics/src/utils/BroadPhaseLayerImpl.hpp
  src/plugin/physics/src/utils/BroadPhaseLayers.hpp
  src/plugin/physics/src/utils/CollisionUtils3D.cpp
  src/plugin/physics/src/utils/CollisionUtils3D.hpp
  src/plugin/physics/src/utils/Layers.hpp
  src/plugin/physics/src/utils/ObjectLayerPairFilterImpl.hpp
  src/plugin/physics/src/utils/ObjectVsBroadPhaseLayerFilterImpl.hpp
  src/plugin/physics/tests/CollisionsTest2D.cpp
  src/plugin/physics/tests/CollisionsTest3D.cpp
  src/plugin/physics/tests/SoftBodyCollisionsTest.cpp
  src/plugin/physics/tests/VelocityIntegrationTest.cpp
  src/plugin/physics/tests/main.cpp
  src/plugin/physics/tests/utils/Sleep.hpp
  src/plugin/physics/xmake.lua
  src/plugin/ui/src/UI.hpp
  src/plugin/ui/src/component/BoxCollider2D.hpp
  src/plugin/ui/src/system/UpdateButtonState.cpp
  src/plugin/ui/src/utils/CollisionUtils2D.cpp
  src/plugin/ui/src/utils/CollisionUtils2D.hpp
  src/plugin/ui/xmake.lua
  xmake.lua
Labels: enhancement, critical

#144 refactor: replace AssetsManager by ResourceManager to use entt resource cache
  src/engine/src/core/Core.hpp
  src/plugin/object/src/Object.hpp
  src/plugin/object/src/component/MeshID.hpp
  src/plugin/object/src/exception/ResourceManagerError.hpp
  src/plugin/object/src/resource/AssetsManager.hpp
  src/plugin/object/src/resource/ResourceManager.hpp
  src/plugin/object/src/utils/AssetID.hpp
  src/plugin/object/tests/AssetsManagerTest.cpp
  src/plugin/object/tests/ResourceManagerTest.cpp
  src/plugin/object/xmake.lua
  src/plugin/opengl/src/resource/FontManager/FontManager.hpp
  src/plugin/opengl/src/resource/GLMeshBufferManager/GLMeshBufferManager.hpp
  src/plugin/opengl/src/resource/GLTextBufferManager/GLTextBufferManager.hpp
  src/plugin/opengl/src/resource/MaterialCache/MaterialCache.hpp
  src/plugin/opengl/src/resource/ShaderManager/ShaderManager.hpp
  src/plugin/opengl/src/system/AllSystems.cpp
  src/plugin/ui/src/component/Sprite2D.hpp
  src/plugin/ui/tests/Button.cpp
Labels: refactor

#157 fix: the ci that stuck after the linter went through
  .github/workflows/linter.yaml
  .github/workflows/mirror.yml
  src/engine/src/core/Core.inl
  src/engine/src/scheduler/SchedulerContainer.inl
Labels: ci

#156 feat(physics): softbody integration
  src/plugin/physics/src/JoltPhysics.hpp
  src/plugin/physics/src/component/SoftBody3D.hpp
  src/plugin/physics/src/plugin/PluginPhysics.cpp
  src/plugin/physics/src/system/PhysicsUpdate.cpp
  src/plugin/physics/src/system/PhysicsUpdate.hpp
  src/plugin/physics/src/utils/SoftBodyCreationSettings.hpp
  src/plugin/physics/src/utils/SoftBodyVertexSettings.hpp
Labels: enhancement

#158 fix: add missing Body header in physics components
  src/plugin/physics/src/component/RigidBody3D.hpp
  src/plugin/physics/src/component/SoftBody3D.hpp
Labels: bug

#161 feat(OpenGL): add a basic colored square in 2D
  src/plugin/opengl/src/OpenGL.hpp
  src/plugin/opengl/src/component/Sprite/Sprite.hpp
  src/plugin/opengl/src/component/SpriteHandle/SpriteHandle.hpp
  src/plugin/opengl/src/plugin/PluginOpenGL.cpp
  src/plugin/opengl/src/resource/GLSpriteBufferManager/GLSpriteBufferManager.hpp
  src/plugin/opengl/src/system/AllSystems.cpp
  src/plugin/opengl/src/system/AllSystems.hpp
  src/plugin/opengl/src/utils/GLSpriteBuffer/GLSpriteBuffer.cpp
  src/plugin/opengl/src/utils/GLSpriteBuffer/GLSpriteBuffer.hpp
  src/plugin/opengl/xmake.lua
Labels: enhancement

#163 refactor(OpenGL): fix sonar errors
  src/plugin/opengl/src/system/AllSystems.cpp
  src/plugin/opengl/src/utils/GLSpriteBuffer/GLSpriteBuffer.cpp
  src/plugin/opengl/src/utils/GLSpriteBuffer/GLSpriteBuffer.hpp
Labels: refactor

#165 refactor(Scene): remove annoying log
  src/plugin/scene/src/resource/SceneManager.cpp
Labels: refactor

#166 fix(OpenGL): normalize color for hlsl
  src/plugin/opengl/src/system/AllSystems.cpp
Labels: bug

#172 feat(System): allow adding system in system's loop
  src/engine/src/system/System.hpp
Labels: bug

#169 feat(Scene): add plugin scene
  src/plugin/scene/src/Scene.hpp
  src/plugin/scene/src/plugin/PluginScene.cpp
  src/plugin/scene/src/plugin/PluginScene.hpp
  src/plugin/scene/xmake.lua
Labels: enhancement

#168 fix(UI): reverse Y axis in UpdateButtonState system
  src/plugin/ui/src/system/UpdateButtonState.cpp
  src/plugin/ui/xmake.lua
Labels: bug

#174 feat(physics): contact callbacks based on entity components
  src/engine/src/entity/Entity.hpp
  src/plugin/physics/src/resource/PhysicsManager.hpp
  src/plugin/physics/src/utils/ContactCallback.hpp
  src/plugin/physics/src/utils/ContactListenerImpl.cpp
  src/plugin/physics/src/utils/ContactListenerImpl.hpp
  src/plugin/physics/src/utils/IContactCallback.hpp
Labels: enhancement

#175 refactor: remove const from contact callbacks
  src/plugin/physics/src/utils/ContactCallback.hpp
  src/plugin/physics/src/utils/IContactCallback.hpp
Labels: refactor

#170 fix: make ui buttons work with current sprite management of opengl
  src/plugin/opengl/src/OpenGL.hpp
  src/plugin/opengl/src/component/Text/Text.hpp
  src/plugin/opengl/xmake.lua
  src/plugin/ui/src/UI.hpp
  src/plugin/ui/src/component/Sprite2D.hpp
  src/plugin/ui/src/system/UpdateButtonTexture.cpp
  src/plugin/ui/tests/Button.cpp
  src/plugin/ui/xmake.lua
Labels: bug

#182 fix(OpenGL): make "updated" bool in mouse button works properly
  src/plugin/window/src/system/WindowSystem.cpp
Labels: bug

#180 feat(Window): add SetTitle to Window resource
  src/plugin/window/src/resource/Window/Window.hpp
Labels: enhancement

#181 feat(Window): add toggle for fullscreen
  src/plugin/window/src/resource/Window/Window.hpp
Labels: enhancement

#179 feat(OpenGL): update viewport and camera when resizing
  src/plugin/opengl/src/plugin/PluginOpenGL.cpp
  src/plugin/opengl/src/system/AllSystems.cpp
  src/plugin/opengl/src/system/AllSystems.hpp
Labels: enhancement

#178 feat(Scheduler): allows to set a default scheduler
  src/engine/src/core/Core.hpp
  src/engine/src/core/Core.inl
  src/engine/src/scheduler/SchedulerContainer.cpp
  src/engine/src/scheduler/SchedulerContainer.hpp
  src/engine/src/scheduler/SchedulerContainer.inl
  src/engine/tests/engine/RegistryTest.cpp
  src/engine/xmake.lua
Labels: enhancement

#184 feat(Core): add before and after dependency in schedulerContainer
  src/engine/src/core/Core.cpp
  src/engine/src/core/Core.hpp
  src/engine/src/scheduler/AScheduler.hpp
  src/engine/src/scheduler/SchedulerContainer.cpp
  src/engine/src/scheduler/SchedulerContainer.hpp
  src/engine/src/scheduler/SchedulerContainer.inl
  src/engine/tests/engine/Scheduler.cpp
Labels: enhancement

#187 feat(Colors): add lightgray_color
  src/plugin/colors/src/utils/Color.hpp
Labels: enhancement

#188 fix(OpenGL): use correct format
  src/plugin/opengl/src/utils/Texture/Texture.cpp
Labels: bug

#186 feat(OpenGL): allow putting texture on sprites
  src/plugin/opengl/src/system/AllSystems.cpp
  src/plugin/opengl/src/utils/GLSpriteBuffer/GLSpriteBuffer.cpp
  src/plugin/opengl/src/utils/GLSpriteBuffer/GLSpriteBuffer.hpp
Labels: enhancement

#194 feat(RenderingPipeline): add rendering pipeline
  src/engine/src/plugin/APlugin.hpp
  src/engine/src/scheduler/SchedulerContainer.cpp
  src/engine/tests/engine/Scheduler.cpp
  src/plugin/opengl/src/plugin/PluginOpenGL.cpp
  src/plugin/opengl/xmake.lua
  src/plugin/rendering-pipeline/.gitignore
  src/plugin/rendering-pipeline/src/RenderingPipeline.hpp
  src/plugin/rendering-pipeline/src/plugin/PluginRenderingPipeline.cpp
  src/plugin/rendering-pipeline/src/plugin/PluginRenderingPipeline.hpp
  src/plugin/rendering-pipeline/src/scheduler/Draw.hpp
  src/plugin/rendering-pipeline/src/scheduler/Init.cpp
  src/plugin/rendering-pipeline/src/scheduler/Init.hpp
  src/plugin/rendering-pipeline/src/scheduler/PreUpdate.hpp
  src/plugin/rendering-pipeline/src/scheduler/RenderSetup.hpp
  src/plugin/rendering-pipeline/src/scheduler/Setup.cpp
  src/plugin/rendering-pipeline/src/scheduler/Setup.hpp
  src/plugin/rendering-pipeline/src/scheduler/ToGPU.hpp
  src/plugin/rendering-pipeline/tests/RenderingPipelineTest.cpp
  src/plugin/rendering-pipeline/tests/main.cpp
  src/plugin/rendering-pipeline/xmake.lua
  src/plugin/window/src/plugin/PluginWindow.cpp
  src/plugin/window/src/plugin/PluginWindow.hpp
  src/plugin/window/xmake.lua
  xmake.lua
Labels: enhancement

#201 feat(UI): implement button image switch
  src/plugin/opengl/src/component/TextureHandle/TextureHandle.hpp
  src/plugin/ui/src/component/Button.hpp
  src/plugin/ui/src/system/UpdateButtonTexture.cpp
Labels: enhancement

#197 refactor(Color): use char rather than float to store channels
  src/plugin/colors/src/utils/Color.hpp
  src/plugin/opengl/src/component/Text/Text.hpp
  src/plugin/opengl/src/system/AllSystems.cpp
Labels: refactor

#198 fix: use bottom-left format for return value of GetMousePosition
  src/plugin/input/src/resource/InputManager.hpp
  src/plugin/ui/src/system/UpdateButtonState.cpp
  src/plugin/window/src/resource/Window/Window.hpp
Labels: bug

#199 feat(input): support callbacks in input manager
  src/plugin/input/src/Input.hpp
  src/plugin/input/src/plugin/PluginInput.cpp
  src/plugin/input/src/plugin/PluginInput.hpp
  src/plugin/input/src/resource/InputManager.hpp
  src/plugin/input/src/system/BindCallbacksToGLFW.cpp
  src/plugin/input/src/system/BindCallbacksToGLFW.hpp
  src/plugin/input/src/utils/InputUtils.hpp
  src/plugin/input/xmake.lua
  src/plugin/opengl/src/OpenGL.hpp
  src/plugin/opengl/src/plugin/PluginOpenGL.cpp
  src/plugin/opengl/src/system/AllSystems.cpp
  src/plugin/opengl/src/system/AllSystems.hpp
  src/plugin/opengl/src/utils/MouseDragging/MouseDragging.hpp
  src/plugin/opengl/xmake.lua
  src/plugin/ui/src/system/UpdateButtonState.cpp
  src/plugin/window/src/plugin/PluginWindow.cpp
  src/plugin/window/src/resource/Button/Buttons.hpp
  src/plugin/window/src/system/WindowSystem.cpp
  src/plugin/window/src/system/WindowSystem.hpp
  src/plugin/window/xmake.lua
Labels: enhancement

#202 refactor(window): using glm ivec2 to handle window size
  src/plugin/window/src/resource/Window/Window.cpp
  src/plugin/window/src/resource/Window/Window.hpp
Labels: refactor

#215 fix: add input plugin as dependency for opengl
  src/plugin/opengl/src/plugin/PluginOpenGL.cpp
Labels: bug
