Repository EngineSquared/EngineSquared, pull requests merged in 2025-05, with the labels that each got.

#213 feat(input): encapsulate joystick polling functions
  src/plugin/input/src/Input.hpp
  src/plugin/input/src/exception/InputError.hpp
  src/plugin/input/src/utils/InputUtils.cpp
  src/plugin/input/src/utils/InputUtils.hpp
  src/plugin/input/xmake.lua
  src/plugin/ui/xmake.lua
Labels: enhancement

#214 feat(log): display entity ids with index and version
  src/engine/src/entity/Entity.hpp
  src/utils/log/src/EntityToIDString.hpp
  src/utils/log/xmake.lua
Labels: enhancement

#218 feat: remove ifdef ES_DEBUG and use proper logging
  src/engine/src/core/Core.cpp
  src/engine/src/core/Core.inl
  src/engine/src/entity/Entity.hpp
  src/engine/src/scheduler/SchedulerContainer.cpp
  src/engine/src/scheduler/SchedulerContainer.inl
  src/engine/xmake.lua
  src/plugin/native-scripting/xmake.lua
  src/plugin/object/src/resource/ResourceManager.hpp
  src/plugin/opengl/src/system/AllSystems.cpp
  src/plugin/opengl/src/utils/GLTextBuffer/GLTextBuffer.cpp
  src/plugin/physics/src/resource/PhysicsManager.hpp
  src/plugin/physics/src/system/PhysicsUpdate.cpp
  src/plugin/physics/src/utils/ContactListenerImpl.cpp
  src/plugin/window/src/resource/Window/Window.cpp
  src/plugin/window/xmake.lua
  src/utils/log/src/Logger.hpp
Labels: enhancement

#220 refactor(OpenGL): removing usage of strerror on MSVC
  src/plugin/opengl/src/utils/Loader/Loader.hpp
  src/utils/log/src/Exception.hpp
Labels: refactor

#219 docs: move CONTRIBUTING.md to the wiki
  CONTRIBUTING.md
Labels: documentation

#217 feat: sound plugin
  src/plugin/sound/.gitignore
  src/plugin/sound/src/plugin/PluginSound.cpp
  src/plugin/sound/src/plugin/PluginSound.hpp
  src/plugin/sound/src/resource/SoundManager.cpp
  src/plugin/sound/src/resource/SoundManager.hpp
  src/plugin/sound/src/system/InitSound.cpp
  src/plugin/sound/src/system/InitSound.hpp
  src/plugin/sound/xmake.lua
  xmake.lua
Labels: enhancement

#216 feat(function-container): store functions in a function-container
  src/engine/src/system/System.hpp
  src/engine/src/system/System.inl
  src/engine/xmake.lua
  src/plugin/input/src/resource/InputManager.hpp
  src/plugin/input/xmake.lua
  src/plugin/opengl/src/system/WindowSystems.cpp
  src/plugin/physics/src/resource/PhysicsManager.hpp
  src/plugin/physics/src/utils/ContactCallback.hpp
  src/plugin/physics/src/utils/ContactListenerImpl.cpp
  src/plugin/physics/src/utils/ContactListenerImpl.hpp
  src/plugin/physics/src/utils/IContactCallback.hpp
  src/utils/function-container/src/BaseFunction.hpp
  src/utils/function-container/src/CallableFunction.hpp
  src/utils/function-container/src/FunctionContainer.hpp
  src/utils/function-container/src/FunctionContainer.inl
  src/utils/function-container/src/FunctionID.hpp
  src/utils/function-container/tests/CallableFunction.cpp
  src/utils/function-container/tests/FunctionContainer.cpp
  src/utils/function-container/tests/main.cpp
  src/utils/function-container/xmake.lua
Labels: enhancement

#226 feat(System): allow to disable systems
  src/engine/src/core/Core.hpp
  src/engine/src/core/Core.inl
  src/engine/src/scheduler/AScheduler.cpp
  src/engine/src/scheduler/AScheduler.hpp
  src/engine/src/scheduler/FixedTimeUpdate.cpp
  src/engine/src/scheduler/IScheduler.hpp
  src/engine/src/scheduler/RelativeTimeUpdate.cpp
  src/engine/src/scheduler/Shutdown.cpp
  src/engine/src/scheduler/Startup.cpp
  src/engine/src/scheduler/Update.cpp
  src/engine/src/system/System.hpp
  src/engine/tests/engine/RegistryTest.cpp
  src/engine/tests/engine/SystemTest.cpp
  src/plugin/input/src/resource/InputManager.hpp
  src/plugin/physics/src/utils/ContactListenerImpl.hpp
  src/plugin/rendering-pipeline/src/scheduler/Init.cpp
  src/plugin/rendering-pipeline/src/scheduler/Setup.cpp
  src/utils/function-container/src/FunctionContainer.hpp
  src/utils/function-container/src/FunctionContainer.inl
  src/utils/function-container/tests/FunctionContainer.cpp
  xmake.lua
Labels: enhancement

#228 refactor(OpenGL): assigning default handles if not provided upon entities creation
  src/plugin/opengl/src/system/RenderSystems.cpp
Labels: refactor

#234 build: set headeronly and object for proper xmake
  src/plugin/camera/xmake.lua
  src/plugin/colors/xmake.lua
  src/plugin/utils/xmake.lua
  src/utils/function-container/xmake.lua
  src/utils/log/xmake.lua
  xmake.lua
Labels: build

#230 fix: plugin bind warning
  src/engine/src/core/Core.hpp
  src/engine/src/core/Core.inl
  src/engine/src/plugin/APlugin.hpp
  src/engine/src/plugin/IPlugin.hpp
Labels: bug

#239 test(Scheduler): add missing dependencies between scheduler
  src/engine/tests/engine/Scheduler.cpp
Labels: bug

#235 fix(OpenGL): dont use non existing default sprite
  src/plugin/opengl/src/system/RenderSystems.cpp
Labels: bug

#227 feat(core): error management of systems
  src/engine/src/core/Core.hpp
  src/engine/src/core/Core.inl
  src/engine/src/scheduler/AScheduler.cpp
  src/engine/src/scheduler/AScheduler.hpp
  src/engine/src/scheduler/FixedTimeUpdate.cpp
  src/engine/src/scheduler/IScheduler.hpp
  src/engine/src/scheduler/RelativeTimeUpdate.cpp
  src/engine/src/scheduler/SchedulerContainer.inl
  src/engine/src/scheduler/Shutdown.cpp
  src/engine/src/scheduler/Startup.cpp
  src/engine/src/scheduler/Update.cpp
  src/engine/src/system/WrappedSystem.hpp
  src/engine/tests/engine/Scheduler.cpp
  src/engine/tests/engine/SystemTest.cpp
  src/plugin/rendering-pipeline/src/scheduler/Init.cpp
  src/plugin/rendering-pipeline/src/scheduler/Setup.cpp
  src/utils/function-container/src/FunctionContainer.hpp
  src/utils/function-container/src/FunctionContainer.inl
Labels: enhancement

#229 feat(physics): allow to set a rigid body as a sensor
  src/plugin/physics/src/component/RigidBody3D.hpp
  src/plugin/physics/src/system/PhysicsUpdate.cpp
Labels: enhancement

#246 feat(Scheduler): use `Time` resource rather than a local time management
  src/engine/src/core/Core.cpp
  src/engine/src/resource/Time.hpp
  src/engine/src/scheduler/FixedTimeUpdate.cpp
  src/engine/src/scheduler/FixedTimeUpdate.hpp
  src/engine/src/scheduler/RelativeTimeUpdate.cpp
  src/engine/src/scheduler/RelativeTimeUpdate.hpp
  src/engine/src/scheduler/Update.cpp
  src/engine/src/scheduler/Update.hpp
  src/engine/tests/engine/FixedUpdateTest.cpp
  src/engine/tests/engine/RelativeUpdateTest.cpp
  src/engine/tests/engine/Scheduler.cpp
  src/engine/xmake.lua
Labels: enhancement

#247 ci: use fixed version of xmake
  .github/workflows/mirror.yml
Labels: ci
