Repository EngineSquared/EngineSquared, pull requests merged in 2025-08, with the labels that each got.

#264 fix(UI): allowing assignment of multiple event listeners per document
  src/plugin/ui/src/resource/UIResource.cpp
  src/plugin/ui/src/resource/UIResource.hpp
  src/plugin/ui/src/system/InitUI.cpp
  src/plugin/ui/src/utils/EventListener.cpp
  src/plugin/ui/src/utils/EventListener.hpp
Labels: bug, refactor

#266 feat(object): add Shape struct and OBJLoader support for shapes
  src/plugin/object/src/resource/OBJLoader.cpp
  src/plugin/object/src/resource/OBJLoader.hpp
  src/plugin/object/src/utils/Shape.hpp
Labels: enhancement

#265 refactor: remove some warnings
  src/engine/src/plugin/IPlugin.hpp
  src/plugin/opengl/src/utils/Loader.hpp
  src/plugin/physics/src/utils/ContactListenerImpl.hpp
Labels: refactor
