Repository EngineSquared/EngineSquared, pull requests merged in 2025-03, with the labels that each got.

#97 feat(Entity): add a ctor with Entity
  src/engine/src/entity/Entity.hpp
Labels: enhancement

#109 feat(AssetsManager): add id key param when adding an asset
  src/plugin/object/src/resource/AssetsManager.hpp
  src/plugin/object/tests/AssetsManagerTest.cpp
  src/plugin/ui/xmake.lua
Labels: enhancement

#116 feat(plugin): integration of Window and VkWrapper plugin systems for Core
  src/plugin/vk-wrapper/src/Vk-Wrapper.hpp
  src/plugin/vk-wrapper/src/command/Command.cpp
  src/plugin/vk-wrapper/src/command/Command.hpp
  src/plugin/vk-wrapper/src/debugMessenger/DebugMessenger.hpp
  src/plugin/vk-wrapper/src/instance/Instance.hpp
  src/plugin/vk-wrapper/src/system/VkWrapperSystems.cpp
  src/plugin/vk-wrapper/src/system/VkWrapperSystems.hpp
  src/plugin/vk-wrapper/src/vkwrapper_config.h
  src/plugin/vk-wrapper/src/wrapper/VkWrapper.cpp
  src/plugin/vk-wrapper/src/wrapper/VkWrapper.hpp
  src/plugin/vk-wrapper/xmake.lua
  src/plugin/window/src/resource/Window.cpp
  src/plugin/window/src/resource/Window.hpp
  src/plugin/window/src/system/WindowSystem.cpp
  src/plugin/window/src/system/WindowSystem.hpp
  src/plugin/window/xmake.lua
  xmake.lua
Labels: enhancement

#124 refactor: detach the vkwrapper from the project
  .github/workflows/mirror.yml
  src/plugin/opengl/xmake.lua
  src/plugin/vk-wrapper/.gitignore
  src/plugin/vk-wrapper/src/Vk-Wrapper.hpp
  src/plugin/vk-wrapper/src/buffers/Buffer.cpp
  src/plugin/vk-wrapper/src/buffers/Buffer.hpp
  src/plugin/vk-wrapper/src/buffers/Texture.cpp
  src/plugin/vk-wrapper/src/buffers/Texture.hpp
  src/plugin/vk-wrapper/src/buffers/UniformObject.hpp
  src/plugin/vk-wrapper/src/buffers/Vertex.cpp
  src/plugin/vk-wrapper/src/buffers/Vertex.hpp
  src/plugin/vk-wrapper/src/command/Command.cpp
  src/plugin/vk-wrapper/src/command/Command.hpp
  src/plugin/vk-wrapper/src/debugMessenger/DebugMessenger.cpp
  src/plugin/vk-wrapper/src/debugMessenger/DebugMessenger.hpp
  src/plugin/vk-wrapper/src/descriptor/Descriptor.cpp
  src/plugin/vk-wrapper/src/descriptor/Descriptor.hpp
  src/plugin/vk-wrapper/src/device/LogicalDevice.cpp
  src/plugin/vk-wrapper/src/device/LogicalDevice.hpp
  src/plugin/vk-wrapper/src/device/PhysicalDevice.cpp
  src/plugin/vk-wrapper/src/device/PhysicalDevice.hpp
  src/plugin/vk-wrapper/src/exception/VkWrapperError.hpp
  src/plugin/vk-wrapper/src/framebuffer/Framebuffer.cpp
  src/plugin/vk-wrapper/src/framebuffer/Framebuffer.hpp
  src/plugin/vk-wrapper/src/graphicsPipeline/GraphicsPipeline.cpp
  src/plugin/vk-wrapper/src/graphicsPipeline/GraphicsPipeline.hpp
  src/plugin/vk-wrapper/src/imageView/ImageView.cpp
  src/plugin/vk-wrapper/src/imageView/ImageView.hpp
  src/plugin/vk-wrapper/src/instance/Instance.cpp
  src/plugin/vk-wrapper/src/instance/Instance.hpp
  src/plugin/vk-wrapper/src/queueFamilies/QueueFamilies.cpp
  src/plugin/vk-wrapper/src/queueFamilies/QueueFamilies.hpp
  src/plugin/vk-wrapper/src/renderPass/RenderPass.cpp
  src/plugin/vk-wrapper/src/renderPass/RenderPass.hpp
  src/plugin/vk-wrapper/src/shaderModule/ShaderModule.cpp
  src/plugin/vk-wrapper/src/shaderModule/ShaderModule.hpp
  src/plugin/vk-wrapper/src/surface/Surface.cpp
  src/plugin/vk-wrapper/src/surface/Surface.hpp
  src/plugin/vk-wrapper/src/swapChain/SwapChain.cpp
  src/plugin/vk-wrapper/src/swapChain/SwapChain.hpp
  src/plugin/vk-wrapper/src/system/VkWrapperSystems.cpp
  src/plugin/vk-wrapper/src/system/VkWrapperSystems.hpp
  src/plugin/vk-wrapper/src/vkwrapper_config.h
  src/plugin/vk-wrapper/src/wrapper/VkWrapper.cpp
  src/plugin/vk-wrapper/src/wrapper/VkWrapper.hpp
  src/plugin/vk-wrapper/xmake.lua
  xmake.lua
Labels: ci, build, refactor

#113 feat(Core): prevent systems from running multiple times
  src/engine/src/core/Core.cpp
  src/engine/src/core/Core.hpp
  src/engine/src/core/Core.inl
  src/engine/src/scheduler/FixedTimeUpdate.cpp
  src/engine/src/scheduler/FixedTimeUpdate.hpp
  src/engine/src/scheduler/IScheduler.hpp
  src/engine/src/scheduler/RelativeTimeUpdate.cpp
  src/engine/src/scheduler/RelativeTimeUpdate.hpp
  src/engine/src/scheduler/Startup.cpp
  src/engine/src/scheduler/Startup.hpp
  src/engine/src/scheduler/Update.cpp
  src/engine/src/scheduler/Update.hpp
  src/engine/src/system/System.hpp
  src/engine/src/system/System.inl
  src/engine/tests/engine/SystemTest.cpp
  src/engine/xmake.lua
  src/plugin/native-scripting/xmake.lua
  src/plugin/physics/xmake.lua
  src/plugin/ui/xmake.lua
  src/plugin/window/xmake.lua
Labels: enhancement

#127 fix(Window): rename CreateWindow system to CreateWindowSystem
  src/plugin/window/src/system/WindowSystem.cpp
  src/plugin/window/src/system/WindowSystem.hpp
Labels: bug

#122 feat(Core): functions to run and stop the core
  src/engine/src/core/Core.cpp
  src/engine/src/core/Core.hpp
  src/engine/xmake.lua
Labels: enhancement

#126 feat(Entity): add parameters to AddTemporaryComponent
  src/engine/src/entity/Entity.hpp
  src/engine/tests/engine/EntityTest.cpp
Labels: enhancement

#129 feat(Scheduler): manage scheduler order with a SchedulerContainer
  src/engine/src/Engine.hpp
  src/engine/src/core/Core.cpp
  src/engine/src/core/Core.hpp
  src/engine/src/core/Core.inl
  src/engine/src/scheduler/AScheduler.hpp
  src/engine/src/scheduler/FixedTimeUpdate.cpp
  src/engine/src/scheduler/FixedTimeUpdate.hpp
  src/engine/src/scheduler/IScheduler.hpp
  src/engine/src/scheduler/RelativeTimeUpdate.cpp
  src/engine/src/scheduler/RelativeTimeUpdate.hpp
  src/engine/src/scheduler/SchedulerContainer.cpp
  src/engine/src/scheduler/SchedulerContainer.hpp
  src/engine/src/scheduler/SchedulerContainer.inl
  src/engine/src/scheduler/Startup.cpp
  src/engine/src/scheduler/Startup.hpp
  src/engine/src/scheduler/Update.cpp
  src/engine/src/scheduler/Update.hpp
  src/engine/tests/engine/Scheduler.cpp
  src/plugin/native-scripting/tests/ScriptTest.cpp
  src/plugin/native-scripting/xmake.lua
  src/plugin/physics/tests/VelocityIntegrationTest.cpp
  src/plugin/relationship/xmake.lua
  src/plugin/scene/xmake.lua
Labels: bug

#134 ci: run on Windows
  .github/workflows/mirror.yml
Labels: ci, build

#130 feat(Plugin): add basic plugin creation with dependencies
  src/engine/src/core/Core.cpp
  src/engine/src/core/Core.hpp
  src/engine/src/core/Core.inl
  src/engine/src/plugin/APlugin.hpp
  src/engine/src/system/System.inl
  src/engine/tests/engine/PluginTest.cpp
  src/engine/xmake.lua
  src/plugin/opengl/src/OpenGL.hpp
  src/plugin/opengl/src/plugin/PluginOpenGL.cpp
  src/plugin/opengl/src/plugin/PluginOpenGL.hpp
  src/plugin/opengl/src/resource/GLFWWindow/GLFWWindow.hpp
  src/plugin/opengl/src/system/AllSystems.cpp
  src/plugin/opengl/src/system/AllSystems.hpp
  src/plugin/opengl/src/utils/Light/Light.hpp
  src/plugin/opengl/src/utils/Material/Material.hpp
  src/plugin/opengl/xmake.lua
Labels: enhancement

#118 feat(Log): add logging in Entity class
  src/engine/src/core/Core.cpp
  src/engine/src/core/Core.hpp
  src/engine/src/entity/Entity.hpp
  src/engine/src/scheduler/SchedulerContainer.cpp
  src/engine/src/scheduler/SchedulerContainer.inl
  src/engine/xmake.lua
  src/plugin/physics/xmake.lua
  src/plugin/scene/tests/SceneTest.cpp
  src/plugin/ui/xmake.lua
  src/utils/log/src/Logger.hpp
Labels: enhancement

#137 feat(Scheduler): add deltatime in update
  src/engine/src/scheduler/Update.cpp
  src/engine/src/scheduler/Update.hpp
Labels: enhancement

#138 refactor(Window, OpenGL): use the Window plugin instead of the wrapper GLFWWindow
  src/plugin/opengl/src/OpenGL.hpp
  src/plugin/opengl/src/plugin/PluginOpenGL.cpp
  src/plugin/opengl/src/resource/GLFWWindow/GLFWWindow.hpp
  src/plugin/opengl/src/system/AllSystems.cpp
  src/plugin/opengl/src/system/AllSystems.hpp
  src/plugin/opengl/xmake.lua
  src/plugin/window/src/resource/Button/Buttons.hpp
  src/plugin/window/src/resource/Window/Window.cpp
  src/plugin/window/src/resource/Window/Window.hpp
  src/plugin/window/src/system/WindowSystem.cpp
  src/plugin/window/src/system/WindowSystem.hpp
  src/plugin/window/xmake.lua
Labels: refactor

#139 fix(NativeScripting): bind `on_destroy` (`entt::registry`) to call `OnDestroy` of `NativeScripting`
  src/plugin/native-scripting/src/component/NativeScripting.hpp
  src/plugin/native-scripting/src/plugin/PluginNativeScripting.cpp
  src/plugin/native-scripting/src/plugin/PluginNativeScripting.hpp
  src/plugin/native-scripting/src/system/ScriptingSystem.cpp
  src/plugin/native-scripting/src/system/ScriptingSystem.hpp
  src/plugin/native-scripting/tests/ScriptTest.cpp
  src/plugin/native-scripting/xmake.lua
Labels: enhancement

#140 refactor(OpenGL): use existing object plugin in opengl
  src/engine/src/scheduler/SchedulerContainer.inl
  src/plugin/object/src/component/Mesh.hpp
  src/plugin/object/src/component/Transform.hpp
  src/plugin/object/src/component/Vertex.hpp
  src/plugin/object/src/resource/OBJLoader.cpp
  src/plugin/object/src/resource/OBJLoader.hpp
  src/plugin/object/tests/OBJLoaderTest.cpp
  src/plugin/object/tests/VertexTest.cpp
  src/plugin/opengl/src/OpenGL.hpp
  src/plugin/opengl/src/component/Model/Model.hpp
  src/plugin/opengl/src/plugin/PluginOpenGL.cpp
  src/plugin/opengl/src/resource/GLBufferManager/GLBufferManager.hpp
  src/plugin/opengl/src/system/AllSystems.cpp
  src/plugin/opengl/src/system/AllSystems.hpp
  src/plugin/opengl/src/utils/GLBuffer/GLBuffer.cpp
  src/plugin/opengl/src/utils/GLBuffer/GLBuffer.hpp
  src/plugin/opengl/src/utils/Loader/Loader.hpp
  src/plugin/opengl/src/utils/Material/Material.hpp
  src/plugin/opengl/src/utils/Mesh/Mesh.hpp
  src/plugin/opengl/xmake.lua
  src/plugin/relationship/xmake.lua
  xmake.lua
Labels: refactor

#132 refactor: replacing usage of std::cout and std::cerr by the logger
  src/plugin/opengl/src/system/AllSystems.cpp
  src/plugin/opengl/src/utils/Loader/Loader.hpp
  src/plugin/opengl/src/utils/Viewer/Viewer.cpp
  src/plugin/scene/src/resource/SceneManager.hpp
Labels: refactor

#141 refactor: renaming all `registry` variables in prototypes to `core`
  src/engine/src/entity/Entity.hpp
  src/engine/src/scheduler/AScheduler.hpp
  src/engine/src/scheduler/FixedTimeUpdate.hpp
  src/engine/src/scheduler/RelativeTimeUpdate.hpp
  src/engine/src/scheduler/Shutdown.hpp
  src/engine/src/scheduler/Startup.hpp
  src/engine/tests/engine/RegistryTest.cpp
  src/engine/tests/engine/RelativeUpdateTest.cpp
  src/plugin/physics/src/component/SoftBodySpring.hpp
  src/plugin/physics/src/system/CollisionCheckerABAB.cpp
  src/plugin/physics/src/system/CollisionCheckerABAB.hpp
  src/plugin/physics/src/system/SoftBodyCollision.cpp
  src/plugin/physics/src/system/SoftBodyCollision.hpp
  src/plugin/physics/src/system/VelocityIntegration.cpp
  src/plugin/physics/src/system/VelocityIntegration.hpp
  src/plugin/scene/src/resource/SceneManager.cpp
  src/plugin/scene/src/resource/SceneManager.hpp
  src/plugin/scene/src/system/UpdateScene.cpp
  src/plugin/scene/src/system/UpdateScene.hpp
  src/plugin/scene/src/utils/AScene.hpp
  src/plugin/ui/src/system/ButtonClick.cpp
  src/plugin/ui/src/system/ButtonClick.hpp
  src/plugin/ui/src/system/UpdateButtonState.cpp
  src/plugin/ui/src/system/UpdateButtonState.hpp
  src/plugin/ui/src/system/UpdateButtonTexture.cpp
  src/plugin/ui/src/system/UpdateButtonTexture.hpp
  src/plugin/ui/tests/Button.cpp
Labels: refactor

#136 refactor: split material, shader and model in new components
  src/plugin/opengl/src/OpenGL.hpp
  src/plugin/opengl/src/component/MaterialHandle/MaterialHandle.hpp
  src/plugin/opengl/src/component/Model/Model.hpp
  src/plugin/opengl/src/component/ModelHandle/ModelHandle.hpp
  src/plugin/opengl/src/component/ShaderHandle/ShaderHandle.hpp
  src/plugin/opengl/src/system/AllSystems.cpp
  src/plugin/opengl/src/system/AllSystems.hpp
  src/plugin/opengl/src/utils/GLBuffer/GLBuffer.cpp
  src/plugin/opengl/src/utils/GLBuffer/GLBuffer.hpp
  src/plugin/opengl/xmake.lua
Labels: refactor

#142 chore: replace some "reg", "registry" to "core"
  src/engine/src/scheduler/AScheduler.hpp
  src/engine/src/scheduler/FixedTimeUpdate.cpp
  src/engine/src/scheduler/RelativeTimeUpdate.cpp
  src/engine/src/scheduler/Shutdown.cpp
  src/engine/src/scheduler/Startup.cpp
  src/engine/src/scheduler/Update.cpp
  src/engine/tests/engine/FixedUpdateTest.cpp
  src/engine/tests/engine/RegistryTest.cpp
  src/engine/tests/engine/RelativeUpdateTest.cpp
  src/engine/tests/engine/Scheduler.cpp
  src/engine/tests/engine/StartupTest.cpp
  src/engine/tests/engine/SystemSetTest.cpp
  src/engine/tests/engine/SystemTest.cpp
  src/plugin/physics/src/system/CollisionCheckerABAB.hpp
  src/plugin/physics/src/system/SoftBodyCollision.hpp
  src/plugin/physics/src/system/VelocityIntegration.hpp
  src/plugin/physics/tests/VelocityIntegrationTest.cpp
  src/plugin/scene/src/resource/SceneManager.hpp
  src/plugin/scene/src/system/UpdateScene.hpp
  src/plugin/scene/src/utils/AScene.hpp
  src/plugin/ui/src/system/ButtonClick.hpp
  src/plugin/ui/src/system/UpdateButtonState.hpp
Labels: question, refactor
